name: myapp
description: "Application de generation de contrat de consentement."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1 # apploication build number
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:   # Dependencies specify other packages that your package needs in order to work.
  flutter:
    sdk: flutter
  http: any
  provider: any
  logger: ^1.0.0
  cupertino_icons: ^1.0.6 # Use with the CupertinoIcons class for iOS style icons.
  firebase_core: ^2.32.0 # Core Firebase functionality
  firebase_auth: ^4.16.0 # Authentication

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0 # The "flutter_lints" package below contains a set of recommended lints to
                        # encourage good coding practices. 

flutter_icons:
  image_path: "assets/icons/logo12x12.png"
  android: true
  ios: true
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/langage/fr.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
