// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlDNbKb6r7YHZFMdc9rVM7q5xhd-ETscI',
    appId: '1:7899806983:web:941b1d8ae0d40d689319a2',
    messagingSenderId: '7899806983',
    projectId: 'consentapp-3b955',
    authDomain: 'consentapp-3b955.firebaseapp.com',
    databaseURL: 'https://consentapp-3b955-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'consentapp-3b955.appspot.com',
    measurementId: 'G-K53NCXJ5G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLuvozFouejt5wiZBrlEsSDwQ3dKL64g0',
    appId: '1:7899806983:android:faa3e39466661fba9319a2',
    messagingSenderId: '7899806983',
    projectId: 'consentapp-3b955',
    databaseURL: 'https://consentapp-3b955-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'consentapp-3b955.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcfb_v3D0cky2AVS4p5fFb3IHq4gezJls',
    appId: '1:7899806983:ios:66e146c0cfb7a71d9319a2',
    messagingSenderId: '7899806983',
    projectId: 'consentapp-3b955',
    databaseURL: 'https://consentapp-3b955-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'consentapp-3b955.appspot.com',
    iosBundleId: 'com.freepartner.consentapp',
  );
}
